### ISSUE TITLE
Create diagram of framework

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/docs#54]
### Description
The docs website visitor wants to get an overview of how the open-sourced packages relate to each other.

It was suggested to use [mermaid](https://mermaid-js.github.io/mermaid/#/) to create the diagrams.

 - [x] Create a basic framework diagram with mermaid
 - [x] Assess/test integration of mermaid into docs repo (consult with @rouille and @jon-hagg )
   - [x] Add mermaid to sphinx with the `sphinxcontrib.mermaid` extension
   - [x] Add dependencies to dockerfile so that the github action can build docs automatically
   - [x] Document requirements for local use 
 - [x] Create PR for mermaid integration into repo
 - [x] Iterate on package relation diagram(s) and create PR

### Acceptance criteria

- Mermaid integrated into docs repo
- Diagram published on the docs website

### Owner 
@ahurli

### Support
@rouille 
@jon-hagg

**Comment by ToddG** [comment]
**mermaid**

https://mermaid-js.github.io/mermaid/#/

**Installation**
The  [cerf readme](https://github.com/Breakthrough-Energy/CERF) has instructions for how to install mermaid:

**Comment by ToddG** [comment]
**markdown linting**

I'm using:
["flake8-rst-docstrings"](https://github.com/Breakthrough-Energy/CERF/blob/dfbf07042adc02ffb8a6b2d07321842eca075c99/noxfile.py#L60)

My [sphinx conf](https://github.com/Breakthrough-Energy/CERF/blob/develop/docs/conf.py) uses ["sphinx.ext.napoleon"](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) to convert google style docstrings to rst. What's interesting is that I can still use RST if I want to, and I do this sort of thing for inserting latex for rendering formulae:

**Comment by ahurli** [comment]
I'm having an issue with the docker build where I'm getting following error when `tox` is run:
```docs_1  | Could not import extension sphinxcontrib.mermaid (exception: cannot import name 'ENOENT' from 'sphinx.util.osutil' (/docs/.tox/prereise/lib/python3.7/site-packages/sphinx/util/osutil.py))```

As far as I can tell, everything loads/installs correctly, but there may be some versioning issues.

**Comment by rouille** [comment]
Not sure to understand what is the issue. I have just checked out `anna/mermaid-diagrams` and inserted the following:
```
.. mermaid::

   sequenceDiagram
      participant Alice
      participant Bob
      Alice->John: Hello John, how are you?
      loop Healthcheck
          John->John: Fight against hypochondria
      end
      Note right of John: Rational thoughts <br/>prevail...
      John-->Alice: Great!
      John->Bob: How about you?
      Bob-->John: Jolly good!
```
which is the example provided [here](https://sphinxcontrib-mermaid-demo.readthedocs.io/en/latest/), into the **index.rst** file. Then I run `tox` and get the following without ant error/warning:
<img width="1234" alt="Screen Shot 2021-05-14 at 6 27 13 PM" src="https://user-images.githubusercontent.com/16549571/118344305-641a8400-b4e2-11eb-935d-dee546b2b208.png">

**Comment by jon-hagg** [comment]
@rouille we needed to use docker initially since there were build errors when running tox directly on github's runners. Not sure if that's still the case, but it's nice to have the build self contained so anyone can run it quickly. It is faster to use tox locally (outside docker), so I'd like to keep both options if possible.

**Comment by jon-hagg** [comment]
@ahurli I think this is the issue we're seeing https://github.com/mgaitan/sphinxcontrib-mermaid/issues/72. Not sure why it only happens in docker, but I got it to work by adding the code snippet suggested there in conf.py

**Comment by rouille** [comment]
> @ahurli I think this is the issue we're seeing [mgaitan/sphinxcontrib-mermaid#72](https://github.com/mgaitan/sphinxcontrib-mermaid/issues/72). Not sure why it only happens in docker, but I got it to work by adding the code snippet suggested there in conf.py

I confirmed that adding:
```
import errno
import sphinx.util.osutil
sphinx.util.osutil.ENOENT = errno.ENOENT
```
to the **conf.py** does the job.

**Comment by ahurli** [comment]
Awesome! Thank you @jon-hagg
