### ISSUE TITLE
Add section in PostREISE tutorial describing scenarios used 

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/docs#59]
# :book:

### Problem
* **Missing**
A section describing the scenarios that are used across the tutorial. This will help the reader interpret results, e.g., why there are less carbon emissions than another, etc.

The section could be located right before the [Analysis of Scenario Data](https://breakthrough-energy.github.io/docs/postreise/index.html#analysis-of-scenario-data) section

### Suggested Improvement
* Write description of the scenarios used in a new file (e.g. **scenarios.rst**) located in **PostREISE/postreise/docs/**
* Include the file in **PostREISE/postreise/docs/index.rst**

**Comment by danielolsen** [comment]
I think this covers all the Scenarios we use in that section, let me know if I missed any:
- Scenario 403 was designed to represent the Eastern interconnect in the year 2020.
- Scenario 3287 was designed to represent the entire U.S. in the year 2030, where there is a large increase in transmission capacity (but no increase across interconnection seams) and carbon-free energy represents approximately 70% of total generation over the course of the year.
- Scenario 2497 was designed to represent the Western interconnect in the year 2030, where 90% of the total energy _could_ come from carbon-free sources, but the transmission network has not been upgraded to accomodate these new clean generation sources. Of this 90% potential, 10% could come from nuclear.
- Scenario 1171 was designed to represent the Western interconnect in the year 2030, with all states meeting their clean energy goals (with 'collaboration' via imports and exports across state lines) and there are 4 GW of energy storage capacity.
- Scenario 3101 was designed to represent the Western interconnect in the year 2030, where 90% of the total energy _does_ come from carbon-free sources, enabled by upgrades in the transmission network to accomodate these new clean generation sources. Of this 90% potential, 10% comes from nuclear.
