### ISSUE TITLE
MIT not a data license

### ISSUE THREAD

**Issue by robbiemorrison** [Breakthrough-Energy/docs#79]
Hi team.  Not sure if this is the correct place to file this issue.

Your wikipedia [entry](https://en.wikipedia.org/wiki/Open_energy_system_models#Breakthrough_Energy_Model) lists [MIT](https://spdx.org/licenses/MIT.html) as the "Data license" in use.  The MIT license is designed for software not data and omits some necessary grants to users.

One such missing grant is the waving of any [96/9/EC database rights](https://en.wikipedia.org/wiki/Database_Directive) that may be present, as legislated in the European Union and currently the United Kingdom.  A better choice would be the Creative Commons CC‑BY‑4.0 license.  Or if you prefer, CC0‑1.0, or some other instrument inbound‑compatible with CC‑BY‑4.0.

Aside from legal non‑suitability, structured data licensed under MIT cannot be mixed and republished with material under CC‑BY‑4.0 — thereby creating a legal silo and preventing the development of a much needed knowledge commons.

Alternatively, this issue may simply be a typo on wikipedia and not representative of project policy?  HTH,&nbsp;R.

**Comment by yixingxu** [comment]
You are right. It is a typo and fixed now. Thanks, @robbiemorrison !
Our dataset license info is also shown on [Zenodo](https://zenodo.org/record/4538590#.Y2l7n-zMJji)
